#!/bin/sh
download=~/Downloads
prefix=/usr/local/cellar

if [ ! -d $download ];
then
	mkdir $download 
fi

cd $download
download
adduser2group www www
adduser2group mysql mysql

echo "Begin install mysql..."
install_mysql

#download source archive.
download() {
	wget http://dev.mysql.com/get/Downloads/MySQL-5.5/mysql-5.5.25.tar.gz/from/http://cdn.mysql.com/ -P $download
	wget http://cn2.php.net/get/php-5.4.4.tar.gz/from/this/mirror
	wget http://nginx.org/download/nginx-1.2.1.tar.gz 
	tar zxvf mysql-5.5.25.tar.gz
	tar zxvf php-5.4.4.tar.gz
	tar zxvf nginx-1.2.1.tar.gz
}

install_mysql() {
	cd $download/mysql-5.5.25
	mysql_installed=`rpm -qa|grep mysql`
	if [ -n $mysql_installed ]  
	then
		echo "old mysql exists, deleted..."
		rpm -e mysql
	fi

  cmake_installed=`rpm -qa|grep cmake`
	if [ -z $cmake_installed ] 
	then
		yum -y install cmake
	else
		echo "check cmake....................yes."
	fi
	
	mkdir /opt/mysql
	mkdir /opt/mysql/data
	mkdir /opt/mysql/log
	mkdir /opt/mysql/etc
	chown -R mysql:mysql /opt/mysql/data
	cmake -DCMAKE_INSTALL_PREFIX=/opt/mysql \
		-DSYSCONFDIR=/opt/mysql/etc \
		-DMYSQL_DATADIR=/opt/mysql/data \
		-DMYSQL_TCP_PORT=3306 \
		-DMYSQL_UNIX_ADDR=/tmp/mysqld.sock \
		-DMYSQL_USER=mysql \
		-DEXTRA_CHARSETS=all \
		-DDEFAULT_CHARSET=utf8 \
		-DDEFAULT_COLLATION=utf8_general_ci \
		-DWITH_READLINE=1 \
		-DWITH_SSL=system \
		-DWITH_EMBEDDED_SERVER=1 \
		-DENABLED_LOCAL_INFILE=1 \
		-DWITH_INNOBASE_STORAGE_ENGINE=1 \
		-DWITHOUT_PARTITION_STORAGE_ENGINE=1
	make;make install
	#initialize
  cp /opt/mysql/support-files/my-medium.cnf /opt/mysql/etc/my.cnf
	chmod 755 scripts/mysql_install_db
	scripts/mysql_install_db --user=mysql --basedir=/opt/mysql/ --datadir=/opt/mysql/data/
	
  cp /opt/mysql/support-files/mysql.server /etc/init.d/mysql
	chmod +x /etc/init.d/mysql

  /etc/init.d/mysql restart

	/opt/mysql/bin/mysqladmin -u root password spvfLy
	/opt/mysql/bin/mysql -uroot -pspvfLy -e 'use mysql;delete from user where password="";flush privileges;exit'

	



}


#create user&group
adduser2group() {
	GROUP=`cat /etc/group|grep $1`
	if [ -z $GROUP ] 
	then
		groupadd $1
	fi
		
	USER=`cat /etc/passwd|grep $2`
	if [ -z $USER ] 
	then
		useradd -g $1 $2
	fi

}


